Repository Gamegoo-repo/Gamegoo-front, pull requests merged in 2024-10, with the labels that each got.

#86 [Feat] 매칭 완료 후 채팅 연결
  src/app/matching/complete/page.tsx
  src/components/chat/Header.tsx
  src/components/chat/MessageList.tsx
  src/components/common/ChatButton.tsx
  src/components/common/Header.tsx
  src/components/common/MoreBox.tsx
  src/components/crBoard/CRModal.tsx
  src/components/readBoard/ReadBoard.tsx
Labels: 💄design, 🛠feat, 🔗api

#89 [Feat] 게시판 / 채팅 수정 및 추가
  src/app/board/page.tsx
  src/app/login/page.tsx
  src/components/board/Table.tsx
  src/components/chat/MessageList.tsx
  src/components/createBoard/PostBoard.tsx
  src/components/match/Profile.tsx
  src/components/readBoard/ReadBoard.tsx
  src/interface/board.ts
Labels: 🛠feat

#94 [Fix] QA #25, #26 수정
  src/components/alert/AlertWindow.tsx
  src/components/mypage/notification/AlertBox.tsx
Labels: 🔧fix

#95 [Feat] 토큰 관련 오류 수정, storage 저장방식 변경, QA 수정
  package-lock.json
  package.json
  src/api/auth.ts
  src/api/index.ts
  src/api/password.ts
  src/api/socket.ts
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/match/profile/page.tsx
  src/app/matching/progress/page.tsx
  src/app/mypage/profile/page.tsx
  src/app/page.tsx
  src/components/common/Header.tsx
  src/components/common/ProtectRoute.tsx
  src/components/match/SquareProfile.tsx
  src/components/mypage/profile/PasswordModal.tsx
  src/styles/GlobalStyles.ts
  src/utils/custom.tsx
  src/utils/storage.ts
Labels: 🔧fix

#98 [Fix] QA 수정
  public/assets/images/champion/no_champion.svg
  public/assets/images/tier/bronze.svg
  public/assets/images/tier/challenger.svg
  public/assets/images/tier/diamond.svg
  public/assets/images/tier/emerald.svg
  public/assets/images/tier/gold.svg
  public/assets/images/tier/grandmaster.svg
  public/assets/images/tier/iron.svg
  public/assets/images/tier/master.svg
  public/assets/images/tier/platinum.svg
  public/assets/images/tier/silver.svg
  public/assets/images/tier/unrank.svg
  public/assets/images/tier/ur.svg
  src/api/board.ts
  src/api/chat.ts
  src/api/friends.ts
  src/api/member.ts
  src/app/join/email/page.tsx
  src/app/mypage/notification/page.tsx
  src/app/mypage/post/page.tsx
  src/app/password/find/page.tsx
  src/components/alert/AlertWindow.tsx
  src/components/board/Table.tsx
  src/components/common/Header.tsx
  src/components/crBoard/User.tsx
  src/components/createBoard/PostBoard.tsx
  src/components/match/Profile.tsx
  src/components/mypage/blocked/BlockedBox.tsx
  src/components/mypage/profile/PasswordModal.tsx
  src/components/readBoard/Champion.tsx
  src/redux/slices/notiSlice.ts
  src/redux/store.ts
Labels: 🔧fix

#99 [Feat] favicon, 페이지명 추가
  src/app/icon.png
  src/app/layout.tsx
Labels: 🛠feat

#100 [Fix] QA
  src/api/manner.ts
  src/app/page.tsx
  src/components/board/Table.tsx
  src/components/chat/ChatLayout.tsx
  src/components/chat/MessageList.tsx
  src/components/common/ChatButton.tsx
  src/components/crBoard/CRModal.tsx
  src/components/match/Profile.tsx
  src/components/readBoard/Champion.tsx
  src/components/readBoard/ReadBoard.tsx
Labels: 🛠feat, 🔧fix

#102 [Fix] 소켓 로그아웃
  src/components/common/Header.tsx
  src/socket.ts
Labels: 🔧fix

#103 [Fix] 매칭 게시판 관련 수정 및 QA
  src/api/manner.ts
  src/app/board/page.tsx
  src/app/matching/complete/page.tsx
  src/components/board/Table.tsx
  src/components/common/Footer.tsx
  src/components/common/FormModal.tsx
  src/components/common/Input.tsx
  src/components/common/MannerLevel.tsx
  src/components/common/MannerLevelBar.tsx
  src/components/common/MannerLevelBox.tsx
  src/components/crBoard/CRModal.tsx
  src/components/crBoard/User.tsx
  src/components/createBoard/PostBoard.tsx
  src/components/match/Profile.tsx
  src/components/readBoard/Champion.tsx
  src/components/readBoard/ReadBoard.tsx
  src/components/user/UserProfile.tsx
  src/data/board.ts
  src/styles/GlobalStyles.ts
  src/utils/custom.tsx
Labels: 🔧fix

#108 [Fix] QA
  public/assets/images/notification/noti_1.svg
  public/assets/images/notification/noti_2.svg
  public/assets/images/notification/noti_3.svg
  public/assets/images/profile/profile_default.svg
  src/api/socket.ts
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/match/profile/page.tsx
  src/app/mypage/notification/page.tsx
  src/app/mypage/post/page.tsx
  src/app/mypage/profile/page.tsx
  src/app/page.tsx
  src/components/alert/AlertWindow.tsx
  src/components/board/Table.tsx
  src/components/chat/ChatRoomItem.tsx
  src/components/chat/FriendItem.tsx
  src/components/chat/Layout.tsx
  src/components/chat/MessageHeader.tsx
  src/components/chat/MessageList.tsx
  src/components/common/ChatButton.tsx
  src/components/common/Header.tsx
  src/components/crBoard/User.tsx
  src/components/createBoard/PostBoard.tsx
  src/components/createBoard/UpdateProfileImage.tsx
  src/components/match/Profile.tsx
  src/components/match/SquareProfile.tsx
  src/components/mypage/blocked/BlockedBox.tsx
  src/components/mypage/notification/AlertBox.tsx
  src/components/mypage/post/Post.tsx
  src/components/mypage/profile/MyPageProfile.tsx
  src/components/readBoard/ProfileImage.tsx
  src/components/user/UserProfile.tsx
  src/hooks/useChatMessage.ts
  src/interface/profile.ts
  src/socket.ts
Labels: 🛠feat, 🔧fix

#111 [Fix] QA
  src/components/board/Table.tsx
Labels: 🔧fix

#113 [Fix] 매칭 게시판 연동, 오류 수정 및 기능 추가
  src/api/user.ts
  src/app/board/page.tsx
  src/app/icon.png
  src/app/layout.tsx
  src/app/match/profile/page.tsx
  src/app/matching/complete/page.tsx
  src/app/matching/progress/page.tsx
  src/components/board/Table.tsx
  src/components/chat/MessageInput.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Footer.tsx
  src/components/createBoard/PostBoard.tsx
  src/components/match/GameStyle.tsx
  src/components/match/Profile.tsx
  src/data/match.ts
  src/redux/slices/boardSlice.ts
  src/redux/slices/chatSlice.ts
  src/redux/slices/userSlice.ts
  src/redux/store.ts
  src/utils/custom.tsx
Labels: 🛠feat, 🔧fix

#114 [Fix] QA
  src/api/chat.ts
  src/app/board/page.tsx
  src/app/mypage/notification/page.tsx
  src/app/mypage/post/page.tsx
  src/app/mypage/review/page.tsx
  src/components/board/Table.tsx
  src/components/chat/ChatLayout.tsx
  src/components/chat/Layout.tsx
  src/components/chat/MessageHeader.tsx
  src/components/chat/MessageList.tsx
  src/components/common/ConfirmModal.tsx
  src/components/crBoard/CRModal.tsx
  src/components/crBoard/PositionBox.tsx
  src/components/createBoard/GameStyle.tsx
  src/components/createBoard/PostBoard.tsx
  src/components/createBoard/UpdateProfileImage.tsx
  src/components/match/Profile.tsx
  src/components/mypage/post/Post.tsx
  src/components/readBoard/GameStyle.tsx
  src/components/readBoard/ReadBoard.tsx
  src/interface/board.ts
  src/interface/chat.ts
Labels: 🛠feat, 🔧fix

#117 [Fix] 오류 수정
  src/api/auth.ts
  src/api/board.ts
  src/api/chat.ts
  src/api/friends.ts
  src/api/join.ts
  src/api/login.ts
  src/api/manner.ts
  src/api/member.ts
  src/api/notification.ts
  src/api/password.ts
  src/api/socket.ts
  src/api/user.ts
  src/app/board/page.tsx
  src/app/guide/page.tsx
  src/app/join/email/page.tsx
  src/app/join/summoner/page.tsx
  src/app/login/page.tsx
  src/app/mypage/profile/page.tsx
  src/app/mypage/review/page.tsx
  src/app/password/auth/page.tsx
  src/app/user/[id]/page.tsx
  src/components/board/Table.tsx
  src/components/chat/ChatLayout.tsx
  src/components/chat/ChatRoomList.tsx
  src/components/chat/FriendItem.tsx
  src/components/chat/FriendList.tsx
  src/components/chat/Layout.tsx
  src/components/chat/MessageList.tsx
  src/components/common/ChatButton.tsx
  src/components/common/Header.tsx
  src/components/common/MannerLevelBox.tsx
  src/components/common/Toggle.tsx
  src/components/createBoard/PostBoard.tsx
  src/components/match/GameStyle.tsx
  src/components/match/Profile.tsx
  src/components/mypage/profile/MyPageProfile.tsx
  src/components/mypage/profile/PasswordModal.tsx
  src/components/socket/SocketConnection.tsx
  src/hooks/useChatFriend.ts
  src/hooks/useChatList.ts
  src/hooks/useChatMessage.ts
  src/interface/chat.ts
  src/interface/manner.ts
  src/redux/slices/userSlice.ts
  src/redux/thunks/postSignIn.ts
  src/socket.ts
Labels: 🛠feat, 🔧fix

#120 [Fix] 회원가입 중복 오류 수정
  src/app/join/summoner/page.tsx
  src/app/login/page.tsx
Labels: 🔧fix

#122 [Design] 마이페이지 헤더 수정
  src/app/mypage/blocked/page.tsx
  src/app/mypage/notification/page.tsx
  src/app/mypage/post/page.tsx
  src/app/mypage/review/page.tsx
  src/app/mypage/service/page.tsx
  src/components/mypage/post/Post.tsx
Labels: 💄design

#125 [Fix] my-message-broadcast-success 이벤트 채팅방 id 검사
  src/hooks/useChatMessage.ts
Labels: 🔧fix

#127 [Fix] 온오프라인 오류 수정
  src/components/chat/MessageHeader.tsx
  src/hooks/useChatFriend.ts
Labels: 🔧fix

#131 [Fix] 더보기 버튼, 게시판 오류 수정
  src/app/board/page.tsx
  src/app/login/page.tsx
  src/components/chat/ChatLayout.tsx
  src/components/chat/ChatRoomList.tsx
  src/components/chat/MessageHeader.tsx
  src/components/common/Header.tsx
  src/components/createBoard/PostBoard.tsx
  src/components/readBoard/ReadBoard.tsx
  src/utils/storage.ts
Labels: 🔧fix

#132 [Fix] 채팅 온오프 친구, 채팅 메시지 오류 수정
  src/components/chat/MessageList.tsx
  src/hooks/useChatFriend.ts
  src/hooks/useChatList.ts
  src/hooks/useChatMessage.ts
Labels: 🔧fix

#134 [Fix] 매너 평가 팝업 오류
  src/components/chat/ChatLayout.tsx
Labels: 🔧fix

#138 [Fix] 매너 평가 시스템 메시지 오류 수정
  src/components/chat/MessageList.tsx
  src/socket.ts
Labels: 🔧fix

#136 [Fix] 소켓 두개 생성 오류
  src/hooks/useChatFriend.ts
  src/hooks/useChatList.ts
  src/hooks/useChatMessage.ts
Labels: 🔧fix

#141 [Fix] 매칭 새로고침 경고 주석처리
  src/app/matching/complete/page.tsx
  src/app/matching/progress/page.tsx
Labels: 🔧fix

#143 [Fix] 게시글 게임 스타일 오류
  src/components/createBoard/PostBoard.tsx
Labels: 🔧fix

#145 [Fix] 기존 QA 및 베타테스트 기반 추가 에러 사항 수정
  public/assets/images/card/board.png
  public/assets/images/card/board.svg
  public/assets/images/card/matching.png
  src/api/friends.ts
  src/app/board/page.tsx
  src/app/layout.tsx
  src/app/match/game-mode/page.tsx
  src/app/match/page.tsx
  src/app/match/profile/page.tsx
  src/app/matching/progress/page.tsx
  src/components/board/Table.tsx
  src/components/chat/ChatLayout.tsx
  src/components/chat/ChatRoomList.tsx
  src/components/common/Box.tsx
  src/components/common/MoreBox.tsx
  src/components/common/PositionCategory.tsx
  src/components/crBoard/CRModal.tsx
  src/components/match/GameStyle.tsx
  src/components/match/Profile.tsx
  src/components/match/SquareProfile.tsx
  src/components/mypage/profile/PasswordModal.tsx
  src/data/match.ts
  src/hooks/notify.ts
  src/interface/board.ts
  src/styles/animation.ts
Labels: 🔧fix

#146 [Fix] Q&A 수정
  src/components/board/Table.tsx
  src/components/chat/ChatLayout.tsx
  src/components/chat/ChatRoomList.tsx
  src/components/chat/Layout.tsx
  src/components/chat/MessageList.tsx
  src/components/common/Alert.tsx
  src/components/common/Box.tsx
  src/components/crBoard/CRModal.tsx
  src/components/createBoard/PostBoard.tsx
  src/components/match/GameStyle.tsx
  src/components/match/Profile.tsx
  src/components/match/SquareProfile.tsx
  src/components/readBoard/ReadBoard.tsx
  src/components/socket/SocketConnection.tsx
  src/hooks/useChatFriend.ts
  src/hooks/useChatMessage.ts
  src/hooks/useJwtError.ts
  src/interface/board.ts
  src/utils/auth.tsx
Labels: 🛠feat, 🔧fix

#149 [Fix] mannerRank 필수 X로 변경
  src/interface/profile.ts
Labels: 🔧fix
