Repository Gamegoo-repo/Gamegoo-front, pull requests merged in 2024-07, with the labels that each got.

#35 [Fix] Input 타입에러 수정
  src/components/common/Input.tsx
Labels: 🔧fix

#37 [Fix] useSearchParams 에러 수정
  src/app/match/game-mode/page.tsx
  src/app/match/profile/page.tsx
Labels: 🔧fix

#38 [Design] 채팅창 UI
  public/assets/icons/favorites.svg
  public/assets/icons/nonFavorites.svg
  public/assets/icons/online.svg
  public/assets/icons/sad.svg
  public/assets/icons/search.svg
  public/assets/icons/smile.svg
  src/app/board/page.tsx
  src/app/guide/page.tsx
  src/app/home/page.tsx
  src/app/match/game-mode/page.tsx
  src/app/match/page.tsx
  src/app/match/profile/page.tsx
  src/app/matching/complete/page.tsx
  src/app/matching/progress/page.tsx
  src/app/user/page.tsx
  src/components/chat/ChatList.tsx
  src/components/chat/ChatRoom.tsx
  src/components/chat/ChatWindow.tsx
  src/components/chat/EvaluationModal.tsx
  src/components/chat/FriendsList.tsx
  src/components/chat/MessageContainer.tsx
  src/components/chat/MiniModal.tsx
  src/components/common/ChatBox.tsx
  src/components/common/ChatButton.tsx
  src/components/common/Checkbox.tsx
  src/components/common/ConfirmModal.tsx
  src/components/common/Dropdown.tsx
  src/components/common/FormModal.tsx
  src/components/common/MannerLevelBox.tsx
  src/components/crBoard/CRModal.tsx
  src/components/readBoard/Report.tsx
  src/data/mannerLevel.ts
  src/libs/dayjs.tsx
  src/redux/slices/confirmModalSlice.ts
  src/redux/slices/mannerStatusSlice.ts
  src/redux/store.ts
  src/styles/theme.ts
  src/utils/custom.tsx
Labels: 💄design, 🛠feat

#40 [Design] 마이페이지 UI
  public/assets/icons/check_circle.svg
  public/assets/images/rank_UR.svg
  src/app/mypage/alert/page.tsx
  src/app/mypage/help/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/post/page.tsx
  src/app/mypage/profile/page.tsx
  src/app/mypage/review/page.tsx
  src/app/mypage/service/page.tsx
  src/components/common/Box.tsx
  src/components/common/Header.tsx
  src/components/common/MannerLevelBar.tsx
  src/components/match/GameStyle.tsx
  src/components/mypage/MypageTab.tsx
  src/components/mypage/PasswordModal.tsx
  src/components/mypage/alert/AlertBox.tsx
  src/components/mypage/post/Post.tsx
  src/components/mypage/profile/MyPageProfile.tsx
  src/components/mypage/profile/PasswordModal.tsx
  src/data/mypage.ts
  src/data/tab.ts
  src/interface/profile.ts
  src/styles/theme.ts
Labels: 💄design

#43 [Feat] 알림창 및 전체적인 UI 반영
  public/assets/icons/logo.svg
  public/assets/icons/logo_m.svg
  public/assets/icons/move.svg
  public/assets/images/profile/profile1.svg
  public/assets/images/profile/profile2.svg
  public/assets/images/profile/profile3.svg
  public/assets/images/profile/profile4.svg
  public/assets/images/profile/profile5.svg
  public/assets/images/profile/profile6.svg
  public/assets/images/profile/profile7.svg
  public/assets/images/profile/profile8.svg
  src/app/guide/page.tsx
  src/app/match/profile/page.tsx
  src/app/matching/progress/page.tsx
  src/app/mypage/blocked/page.tsx
  src/app/mypage/profile/page.tsx
  src/app/user/page.tsx
  src/components/alert/AlertWindow.tsx
  src/components/common/ConfirmModal.tsx
  src/components/common/FormModal.tsx
  src/components/common/Header.tsx
  src/components/common/MoreBox.tsx
  src/components/common/PositionCategory.tsx
  src/components/crBoard/PositionBox.tsx
  src/components/match/GameStyle.tsx
  src/components/match/Profile.tsx
  src/components/match/SelectedStylePopup.tsx
  src/components/match/SquareProfile.tsx
  src/components/mypage/alert/AlertBox.tsx
  src/components/mypage/blocked/BlockedBox.tsx
  src/components/mypage/post/Post.tsx
  src/components/mypage/profile/MyPageProfile.tsx
  src/components/mypage/profile/PasswordModal.tsx
  src/components/readBoard/Report.tsx
  src/data/mypage.ts
  src/data/tab.ts
Labels: 💄design, 🛠feat

#44 [Design] 채팅창 작은 모달 UI
  public/assets/icons/default_top.svg
  src/app/board/page.tsx
  src/app/guide/page.tsx
  src/app/home/page.tsx
  src/app/match/game-mode/page.tsx
  src/app/match/page.tsx
  src/app/match/profile/page.tsx
  src/app/matching/complete/page.tsx
  src/app/matching/progress/page.tsx
  src/app/mypage/profile/page.tsx
  src/components/board/PositionFilter.tsx
  src/components/chat/ChatList.tsx
  src/components/chat/ChatRoom.tsx
  src/components/chat/ChatWindow.tsx
  src/components/chat/DeleteFriend.tsx
  src/components/chat/FriendsList.tsx
  src/components/chat/MessageContainer.tsx
  src/components/chat/MiniModal.tsx
  src/components/common/ConfirmModal.tsx
  src/components/common/Dropdown.tsx
  src/components/common/FormModal.tsx
  src/components/common/MannerLevel.tsx
  src/components/match/Profile.tsx
  src/components/match/SquareProfile.tsx
  src/redux/slices/confirmModalSlice.ts
  src/redux/slices/modalSlice.ts
  src/redux/store.ts
  src/utils/custom.tsx
Labels: 💄design, 🛠feat

#48 [Chore] riot.txt 파일 위치 수정
  .env
  .gitignore
  public/riot.txt
Labels: ⚙chore

#50 [Feat] 회원가입, 로그인 API 연동
  .gitignore
  src/api/.gitkeep
  src/api/index.ts
  src/api/join.ts
  src/api/login.ts
  src/app/board/page.tsx
  src/app/home/page.tsx
  src/app/join/email/page.tsx
  src/app/join/layout.tsx
  src/app/join/password/page.tsx
  src/app/join/summoner/page.tsx
  src/app/layout.tsx
  src/app/match/page.tsx
  src/app/matching/progress/page.tsx
  src/app/page.tsx
  src/components/chat/ChatRoom.tsx
  src/components/common/Button.tsx
  src/components/common/ChatButton.tsx
  src/components/common/Checkbox.tsx
  src/components/common/ConfirmModal.tsx
  src/components/common/FormModal.tsx
  src/components/common/GameStylePopup.tsx
  src/components/common/Header.tsx
  src/components/match/GraphicBox.tsx
  src/components/match/Profile.tsx
  src/components/match/SelectedStylePopup.tsx
  src/constants/regEx.ts
  src/data/match.ts
  src/interface/.gitkeep
  src/redux/slices/exampleSlice.ts
  src/redux/slices/signInSlice.ts
  src/redux/store.ts
  src/redux/thunks/.gitkeep
  src/redux/thunks/postSignIn.ts
  src/styles/GlobalStyles.ts
Labels: 🛠feat, 🔗api
