Repository Gamegoo-repo/Gamegoo-front, pull requests merged in 2025-03, with the labels that each got.

#201 [Feat] 로그아웃 오류 수정 및 비회원 접근 가능 영역 확장
  public/assets/icons/chevron_left.svg
  src/api/login/logout.ts
  src/app/match/page.tsx
  src/app/page.tsx
  src/components/chat/ChatLayout.tsx
  src/components/chat/ChatRoomItem.tsx
  src/components/chat/ChatRoomList.tsx
  src/components/chat/Layout.tsx
  src/components/chat/MessageHeader.tsx
  src/components/chat/MessageInput.tsx
  src/components/chat/MessageList.tsx
  src/components/match/GraphicBox.tsx
  src/components/match/Profile.tsx
  src/components/readBoard/ReadBoard.tsx
  src/middleware.ts
Labels: 🛠feat, 🔧fix

#205 [Feat] 찾는 포지션 설정 방식 변경
  src/api/manner/manner.ts
  src/app/mypage/review/page.tsx
  src/app/user/[id]/page.tsx
  src/components/board/Table.tsx
  src/components/chat/ChatLayout.tsx
  src/components/chat/Layout.tsx
  src/components/common/ConfirmModal.tsx
  src/components/common/MannerLevelBox.tsx
  src/components/common/PositionCategory.tsx
  src/components/crBoard/PositionBox.tsx
  src/components/createBoard/PostBoard.tsx
  src/components/match/Profile.tsx
  src/components/readBoard/ReadBoard.tsx
  src/components/user/UserProfile.tsx
  src/constants/position.ts
  src/data/profile/default.ts
  src/interface/board.ts
  src/interface/profile.ts
  src/redux/slices/matchInfo.ts
  src/redux/slices/userSlice.ts
  src/types/api/user/profile/get.d.ts
  src/types/api/user/profile/put.d.ts
  src/types/position/position.d.ts
Labels: 🛠feat, 💻refactor

#210 [Design] 매너평가 반응형 작업
  src/components/chat/MessageList.tsx
  src/styles/theme.ts
Labels: 💄design

#212 [Refactor] 채팅창 드래그 관련 함수 useDrag 커스텀 훅으로 분리
  src/components/chat/Layout.tsx
  src/hooks/useDrag.ts
Labels: 💻refactor

#217 [Chore] Vercel 배포 시 PR 미리보기 설정
  .github/workflows/preview.yml
Labels: ⚙chore

#218 [Design] 매칭 반응형작업 - header 작업
  public/assets/icons/chat.svg
  src/components/chat/Layout.tsx
  src/components/common/ChatButton.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/constants/position.ts
  src/hooks/useMediaQueries.ts
  src/styles/theme.ts
  src/types/position/position.d.ts
Labels: 💄design
