Repository Gamegoo-repo/Gamegoo-front, pull requests merged in 2025-07, with the labels that each got.

#296 [Style] 채팅 메세지 전송 시 애니메이션 효과 추가
  src/components/chat/ChatRoomItem.tsx
  src/components/chat/MessageHeader.tsx
  src/components/chat/MessageList.tsx
Labels: 💄design

#297 [Refactor] Post 공용 컴포넌트 리팩토링
  src/app/mypage/post/page.tsx
  src/components/board/PostList.tsx
  src/components/board/Table.tsx
  src/components/common/Champion.tsx
  src/components/common/PostItem/ChampionSection.tsx
  src/components/common/PostItem/MemoSection.tsx
  src/components/common/PostItem/PositionSection.tsx
  src/components/common/PostItem/PostItem.tsx
  src/components/common/PostItem/PostItemModal.tsx
  src/components/common/PostItem/UserSection/ProfileImage.tsx
  src/components/common/PostItem/UserSection/UserNManner.tsx
  src/components/common/PostItem/UserSection/UserSection.tsx
  src/components/common/PostItem/UserSection/index.ts
  src/components/common/PostItem/UserTierSection.tsx
  src/components/common/PostItem/hooks/index.ts
  src/components/common/PostItem/hooks/useAlert.ts
  src/components/common/PostItem/hooks/useBlockActions.ts
  src/components/common/PostItem/hooks/useFriendActions.ts
  src/components/common/PostItem/hooks/useMoreBoxMenu.ts
  src/components/common/PostItem/hooks/usePostActions.ts
  src/components/common/PostItem/hooks/useUIHandlers.ts
  src/components/common/PostItem/index.ts
  src/components/mypage/post/MoPost.tsx
  src/components/mypage/post/Post.tsx
  src/components/profile/Profile.tsx
  src/components/readBoard/Champion.tsx
  src/components/readBoard/ReadBoard.tsx
  src/components/user/UserProfile.tsx
Labels: 🔧fix, 💻refactor

#302 [Design] 챔피언, 포지션 선택 박스 모바일 반응형
  src/api/board/board.ts
  src/components/common/Banner.tsx
  src/components/common/Champion.tsx
  src/components/common/PositionCategory.tsx
  src/components/profile/Profile.tsx
  src/components/user/UserProfile.tsx
  src/data/profile/default.ts
  src/interface/profile.ts
  src/types/api/champion/champion.ts
Labels: 💄design, 🔧fix

#312 [Fix] 더보기 버튼 재클릭 시 닫히지 않고 다시 나오는 오류 수정
  src/components/common/MoreBox.tsx
  src/components/common/PostItem/UserSection/UserSection.tsx
  src/components/user/UserProfile.tsx
Labels: 🔧fix

#311 [Refactor] storage 관련 변수 정리 및 적용
  src/api/auth.ts
  src/api/socket.ts
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/mypage/post/page.tsx
  src/app/riot/callback/page.tsx
  src/app/riot/page.tsx
  src/components/chat/ChatLayout.tsx
  src/components/common/ChatButton.tsx
  src/components/common/Header.tsx
  src/components/socket/SocketConnection.tsx
  src/constants/storage.ts
  src/hooks/useChatMessage.ts
  src/hooks/useJwtError.ts
  src/socket.ts
  src/utils/storage.ts
Labels: 💻refactor

#324 [Design] 모바일 게시글 로딩 시 스켈레톤 UI 적용 및 Table 컴포넌트 분리
  src/app/board/page.tsx
  src/app/match/profile/page.tsx
  src/app/matching/complete/page.tsx
  src/app/matching/progress/page.tsx
  src/components/board/PostList.tsx
  src/components/board/Table.tsx
  src/components/board/Table/TableHead.tsx
  src/components/board/Table/TableRow.tsx
  src/components/board/Table/cells/ChampionCell.tsx
  src/components/board/Table/cells/ContentCell.tsx
  src/components/board/Table/cells/MannerLevelCell.tsx
  src/components/board/Table/cells/MoreCell.tsx
  src/components/board/Table/cells/PositionCell.tsx
  src/components/board/Table/cells/ProfileCell.tsx
  src/components/board/Table/cells/TierCell.tsx
  src/components/board/Table/cells/WantPositionCell.tsx
  src/components/board/Table/cells/WinRateCell.tsx
  src/components/common/PostItem/SkeletonPostItem.tsx
  src/components/common/Skeleton.tsx
  src/components/mypage/post/MoPost.tsx
  src/types/board/table.d.ts
Labels: 💄design, 💻refactor

#328 [Fix] 모바일에서 채팅 동작 개선
  src/app/layout.tsx
  src/components/chat/ChatLayout.tsx
  src/components/chat/FriendItem.tsx
  src/components/chat/MessageHeader.tsx
  src/components/chat/MessageInput.tsx
  src/components/chat/MessageList.tsx
Labels: 🔧fix

#332 [Refactor] Profile 컴포넌트 분리 리팩토링
  src/app/matching/progress/page.tsx
  src/components/board/Table/cells/TierCell.tsx
  src/components/common/Header.tsx
  src/components/common/RankTier.tsx
  src/components/match/SquareProfile.tsx
  src/components/mypage/post/Post.tsx
  src/components/profile/Profile.tsx
  src/components/profile/Profile/ProfilePositionSection.tsx
  src/components/profile/Profile/hooks/useBlock.tsx
  src/components/profile/Profile/hooks/useFriend.tsx
  src/components/profile/Profile/hooks/useMike.tsx
  src/components/profile/Profile/hooks/useMoreBoxOutsideClick.tsx
  src/components/profile/Profile/hooks/usePosition.tsx
  src/components/profile/Profile/hooks/useProfileImage.tsx
  src/components/profile/Profile/hooks/useReport.tsx
  src/types/api/board/board.d.ts
  src/utils/custom.tsx
Labels: 💻refactor

#327 [Refactor] z-index 공통화 및 리팩토링
  src/app/match/game-mode/page.tsx
  src/app/match/page.tsx
  src/components/alert/AlertWindow.tsx
  src/components/board/Table.tsx
  src/components/chat/DeleteFriend.tsx
  src/components/chat/Layout.tsx
  src/components/common/Alert.tsx
  src/components/common/BottomModal.tsx
  src/components/common/Champion.tsx
  src/components/common/ConfirmModal.tsx
  src/components/common/Dropdown.tsx
  src/components/common/FormModal.tsx
  src/components/common/Header.tsx
  src/components/common/Input.tsx
  src/components/common/MannerLevelBar.tsx
  src/components/common/MannerLevelBox.tsx
  src/components/common/MoreBox.tsx
  src/components/common/PositionCategory.tsx
  src/components/common/PostItem/SkeletonPostItem.tsx
  src/components/common/PostItem/UserSection/UserSection.tsx
  src/components/common/Skeleton.tsx
  src/components/common/TermModal.tsx
  src/components/common/Tooltip.tsx
  src/components/crBoard/CRModal.tsx
  src/components/crBoard/UserAccount.tsx
  src/components/createBoard/GameStyle.tsx
  src/components/createBoard/PostBoard.tsx
  src/components/match/SelectedStylePopup.tsx
  src/components/mypage/profile/PasswordModal.tsx
  src/components/profile/UpdateProfileImage.tsx
  src/components/readBoard/ReadBoard.tsx
  src/components/readBoard/WinningRate.tsx
  src/constants/match.ts
  src/styles/theme.ts
Labels: 🔧fix, 💻refactor

#333 [Fix] 라이엇 로그인 이후 로그인 상태 유지 및 소켓 초기화 오류 수정
  src/app/join/terms/page.tsx
  src/app/login/page.tsx
  src/app/riot/callback/page.tsx
  src/app/riot/page.tsx
  src/constants/ko.json
  src/constants/storage.ts
  src/utils/storage.ts
Labels: 🔧fix

#334 [Feat] 신고 횟수 제한 모달 추가
  src/components/readBoard/ReportModal.tsx
Labels: 🛠feat

#336 [Chore] Babelrc 파일 삭제
  .babelrc
  package-lock.json
  package.json
Labels: ⚙chore

#339 [Chore] git hook으로 precommit 설정 (이슈 번호 태그 자동화)
  .githooks/prepare-commit-msg
  package-lock.json
  package.json
Labels: ⚙chore

#341 [Refactor] ConfirmModal context로 리팩토링
  src/app/board/page.tsx
  src/app/join/summoner/page.tsx
  src/app/layout.tsx
  src/app/match/profile/page.tsx
  src/app/matching/complete/page.tsx
  src/app/matching/progress/page.tsx
  src/app/mypage/profile/page.tsx
  src/components/board/Table.tsx
  src/components/chat/ChatLayout.tsx
  src/components/chat/Layout.tsx
  src/components/chat/MessageList.tsx
  src/components/common/PostItem/PostItemModal.tsx
  src/components/createBoard/PostBoard.tsx
  src/components/mypage/blocked/BlockedBox.tsx
  src/components/mypage/post/Post.tsx
  src/components/profile/Profile.tsx
  src/components/readBoard/ReadBoard.tsx
  src/components/readBoard/WinningRate.tsx
  src/constants/match.ts
  src/constants/storage.ts
  src/contexts/ConfirmModalContext.tsx
  src/hooks/index.ts
  src/hooks/useConfirmModalContext.ts
  src/styles/theme.ts
  src/types/modal/confirmModal.d.ts
Labels: 💻refactor

#347 [Refactor] 무한스크롤 기능 useInfiniteScroll 훅 생성
  src/app/board/page.tsx
  src/app/mypage/post/page.tsx
  src/components/alert/AlertWindow.tsx
  src/hooks/index.ts
  src/hooks/useInfiniteScroll.ts
  src/hooks/useMediaQueries.ts
Labels: 💻refactor

#348 [Fix] 라이엇 로그인 시 소켓 로그인 오류 수정
  src/api/auth.ts
  src/app/riot/callback/page.tsx
Labels: 🔧fix

#349 [Refactor] Tailwind CSS 적용 및 글로벌 리셋 코드 정리
  package-lock.json
  package.json
  postcss.config.mjs
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/redux/slices/signInSlice.ts
  src/styles/GlobalStyles.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: ⚙chore

#351 [Fix] 게시판 UI 오류 수정
  src/app/mypage/post/page.tsx
  src/components/board/Table.tsx
  src/components/board/Table/TableRow.tsx
  src/components/board/Table/cells/ChampionCell.tsx
  src/components/board/Table/cells/MannerLevelCell.tsx
  src/components/board/Table/cells/MoreCell.tsx
  src/components/board/Table/cells/ProfileCell.tsx
  src/components/common/Champion.tsx
  src/components/common/MoreBox.tsx
  src/components/common/PostItem/PostItem.tsx
  src/components/common/PostItem/UserSection/UserSection.tsx
  src/components/mypage/post/Post.tsx
  src/components/readBoard/MoreBoxButton.tsx
  src/components/readBoard/ReadBoard.tsx
  src/styles/theme.ts
Labels: 🔧fix

#361 [Fix] 토큰 재발급 설정
  src/app/mypage/notification/page.tsx
  src/utils/api.ts
  src/utils/auth.tsx
  src/utils/authMiddleware.ts
Labels: 🔧fix, 🔗api

#363 [Fix] 게시글 신고 오류
  src/components/board/PostList.tsx
  src/components/common/FormModal.tsx
  src/components/common/PostItem/PostItem.tsx
  src/components/common/PostItem/hooks/useMoreBoxMenu.ts
  src/components/profile/Profile.tsx
  src/components/profile/Profile/hooks/useReport.tsx
  src/components/readBoard/ReportModal.tsx
  src/utils/authMiddleware.ts
Labels: 🔧fix
