Repository Gamegoo-repo/Gamegoo-front, pull requests merged in 2025-06, with the labels that each got.

#258 [Feat] 내가 찾는 포지션 2개 변경 적용
  src/components/common/PositionCategory.tsx
  src/components/crBoard/PositionBox.tsx
  src/components/match/Profile.tsx
  src/components/mypage/post/PositionBox.tsx
Labels: 🛠feat

#262 [Design] 게시판 UI 반응형
  public/assets/icons/blocked.svg
  public/assets/icons/chevron_double_up_white.svg
  src/app/board/page.tsx
  src/components/board/PositionFilter.tsx
  src/components/board/PostList.tsx
  src/components/board/Table.tsx
  src/components/common/Button.tsx
  src/components/common/Checkbox.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Header.tsx
  src/components/common/MannerLevel.tsx
  src/components/crBoard/CRModal.tsx
  src/components/crBoard/UserAccount.tsx
  src/components/createBoard/GameStyle.tsx
  src/components/createBoard/PostBoard.tsx
  src/components/createBoard/UpdateProfileImage.tsx
  src/components/readBoard/Champion.tsx
  src/components/readBoard/GameStyle.tsx
  src/components/readBoard/MoreBoxButton.tsx
  src/components/readBoard/ProfileImage.tsx
  src/components/readBoard/ReadBoard.tsx
  src/components/readBoard/ReportModal.tsx
  src/constants/tab.ts
  src/styles/theme.ts
  src/types/api/board/board.d.ts
  src/utils/string.tsx
Labels: 💄design

#272 [Design] 모바일 이미지 화질 개선 및 폰트 preload 적용
  public/assets/fonts/TimeForSalad.ttf
  public/assets/images/card/board.png
  public/assets/images/card/board_mo.png
  public/assets/images/card/board_mo.svg
  public/assets/images/card/matching.png
  public/assets/images/card/matching_mo.png
  public/assets/images/card/matching_mo.svg
  src/app/layout.tsx
  src/app/mypage/profile/page.tsx
  src/app/mypage/service/page.tsx
  src/components/common/Banner.tsx
  src/styles/GlobalStyles.tsx
  src/styles/fonts.ts
Labels: 💄design, 🤝🏻style

#271 [Fix] 매칭 중 동시 접속 인원 반영 오류 수정
  src/app/match/profile/page.tsx
  src/app/matching/complete/page.tsx
  src/app/matching/progress/page.tsx
Labels: 🔧fix

#276 [Fix] 매칭 서버 변경사항 반영 및 오류 수정
  src/app/join/layout.tsx
  src/app/match/profile/page.tsx
  src/app/matching/complete/page.tsx
  src/app/matching/progress/page.tsx
  src/app/mypage/profile/page.tsx
  src/components/board/PostList.tsx
  src/components/board/Table.tsx
  src/components/common/Header.tsx
  src/components/crBoard/PositionBox.tsx
  src/components/createBoard/PostBoard.tsx
  src/components/match/SquareProfile.tsx
  src/components/mypage/post/MoPost.tsx
  src/components/profile/Profile.tsx
  src/components/readBoard/ReadBoard.tsx
  src/components/readBoard/ReportModal.tsx
  src/constants/match.ts
  src/constants/tab.ts
  src/utils/matching/threshold.tsx
Labels: 🛠feat

#283 [Fix] generate script esmodule 오류
  package.json
  scripts/generate-api.ts
  scripts/lib/types.d.ts
Labels: 🔧fix

#292 [Style] 이용약관 페이지 스타일 수정
  src/app/policy/layout.tsx
  src/components/common/CategoryToggle.tsx
Labels: 💄design

#294 [Style] 매칭 태블릿 반응형, alert 컴포넌트 모바일 반응형 적용
  src/components/common/Alert.tsx
  src/components/profile/Profile.tsx
Labels: 💄design
