Repository Gamegoo-repo/Gamegoo-front, pull requests merged in 2025-08, with the labels that each got.

#372 [Refactor] 게시판 페이지 리팩토링
  package-lock.json
  package.json
  public/assets/icons/board/positionIcons.ts
  public/assets/icons/board/punch.svg
  public/assets/icons/board/reload.svg
  src/app/board/page.tsx
  src/components/board/Table.tsx
  src/components/board/Table/TableHead.tsx
  src/components/board/Table/TableRow.tsx
  src/components/board/Table/cells/ChampionCell.tsx
  src/components/board/Table/cells/ContentCell.tsx
  src/components/board/Table/cells/MannerLevelCell.tsx
  src/components/board/Table/cells/PositionCell.tsx
  src/components/board/Table/cells/ProfileCell.tsx
  src/components/board/Table/cells/ProfileImage.tsx
  src/components/board/Table/cells/TierCell.tsx
  src/components/board/Table/cells/WantPositionCell.tsx
  src/components/board/Table/cells/WinRateCell.tsx
  src/components/common/Champion.tsx
Labels: 💄design

#379 [Chore] vercel workflow 삭제 & 빌드 체크 CI 추가
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .github/workflows/preview.yml
Labels: ⚙chore

#382 [Fix] 회원 차단/차단해제 상태관리
  src/components/board/Table.tsx
  src/components/readBoard/ReadBoard.tsx
Labels: 🔧fix

#383 [Fix] 끌어올리기 오류 수정
  src/app/board/page.tsx
Labels: 🔧fix

#389 [Feat] 겜구 서비스 소개 모달 추가
  package-lock.json
  package.json
  public/assets/images/preview/m1.json
  public/assets/images/preview/m2.json
  public/assets/images/preview/m3.json
  src/app/page.tsx
  src/components/common/GuideModal.tsx
Labels: 🛠feat
