Repository Gamegoo-repo/Gamegoo-front, pull requests merged in 2025-05, with the labels that each got.

#238 [Feat] 소환사명 없을 경우 회원가입 오류 처리
  src/app/riot/callback/page.tsx
  src/constants/messages.ts
Labels: 🛠feat

#240 [Design] 매칭 프로필 UI 변경사항 적용, 내가 찾는 포지션 2개 설정
  src/api/board/board.ts
  src/app/matching/complete/page.tsx
  src/app/matching/progress/page.tsx
  src/components/common/Box.tsx
  src/components/common/PositionCategory.tsx
  src/components/common/RankTier.tsx
  src/components/crBoard/CRModal.tsx
  src/components/crBoard/PositionBox.tsx
  src/components/createBoard/PostBoard.tsx
  src/components/match/Profile.tsx
  src/components/match/SquareProfile.tsx
  src/constants/messages.ts
Labels: 💄design, 🛠feat

#241 [Feat] 새로고침 시 채팅 탭 유지
  package-lock.json
  package.json
  src/app/layout.tsx
  src/components/chat/MessageHeader.tsx
  src/redux/slices/chatSlice.ts
  src/redux/store.ts
Labels: 🛠feat, 🔧fix

#243 [Design] 유저 프로필 페이지 반응형
  public/assets/icons/check_level_ring.svg
  src/components/common/Box.tsx
  src/components/common/HeaderTitle.tsx
  src/components/common/MannerLevelBar.tsx
  src/components/common/Mic.tsx
  src/components/match/GameStyle.tsx
  src/components/match/Profile.tsx
  src/components/match/SquareProfile.tsx
  src/components/readBoard/Champion.tsx
  src/components/readBoard/ReadBoard.tsx
  src/components/user/BlindProfile.tsx
  src/components/user/UserProfile.tsx
  src/styles/theme.ts
Labels: 💄design

#245 [Design] 채팅 반응형 UI 적용
  src/components/chat/ChatFriendList.tsx
  src/components/chat/ChatLayout.tsx
  src/components/chat/ChatRoomItem.tsx
  src/components/chat/ChatRoomList.tsx
  src/components/chat/Layout.tsx
  src/components/chat/MessageHeader.tsx
  src/components/chat/MessageInput.tsx
  src/components/chat/MessageList.tsx
  src/components/chat/SearchBar.tsx
  src/components/chat/Tabs.tsx
  src/components/common/MoreBox.tsx
  src/redux/slices/chatSlice.ts
  src/types/api/chat/chat.d.ts
Labels: 💄design

#247 [Design] 팝업 PC, MO 디자인 수정 적용
  src/app/mypage/profile/page.tsx
  src/components/common/ConfirmModal.tsx
Labels: 💄design

#250 style(#249): 알림 반응형 적용
  src/components/alert/AlertWindow.tsx
  src/components/common/Header.tsx
  src/constants/tab.ts
Labels: 💄design

#252 [Design] 내정보 UI 반응형
  public/assets/icons/info.svg
  public/assets/icons/riot_red.svg
  src/app/mypage/blocked/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/notification/page.tsx
  src/app/mypage/post/page.tsx
  src/app/mypage/profile/page.tsx
  src/app/mypage/review/page.tsx
  src/app/mypage/service/page.tsx
  src/components/common/Box.tsx
  src/components/common/Header.tsx
  src/components/common/MannerLevel.tsx
  src/components/common/MannerLevelBar.tsx
  src/components/common/RankTier.tsx
  src/components/common/Toggle.tsx
  src/components/match/GameStyle.tsx
  src/components/mypage/blocked/BlockedBox.tsx
  src/components/mypage/notification/AlertBox.tsx
  src/components/mypage/post/Champion.tsx
  src/components/mypage/post/MoPost.tsx
  src/components/mypage/post/PositionBox.tsx
  src/components/mypage/post/Post.tsx
  src/components/mypage/post/ProfileImage.tsx
  src/components/mypage/profile/MyPageProfile.tsx
  src/styles/theme.ts
Labels: 💄design
