Repository Gamegoo-repo/Gamegoo-front, pull requests merged in 2025-01, with the labels that each got.

#165 [Feat] 이용 약관 및 개인정보 보호 페이지 제작
  src/app/policy/layout.tsx
  src/app/policy/page.tsx
  src/components/common/CategoryToggle.tsx
  src/components/common/Footer.tsx
  src/styles/theme.ts
Labels: 💄design, 🛠feat

#166 [Fix] useSearchParams 클라이언트 실행을 위한 Suspense 설정
  src/app/policy/layout.tsx
Labels: 🔧fix

#167 [Fix] policy 페이지 Suspense 내 children 추가
  src/app/policy/layout.tsx
Labels: 🔧fix

#162 [Feat] 회원 관련 서버 API ver2 재연결
  src/api/auth.ts
  src/api/chat.ts
  src/api/email/email.ts
  src/api/index.ts
  src/api/join.ts
  src/api/join/join.ts
  src/api/join/riot.ts
  src/api/login.ts
  src/api/login/login.ts
  src/api/login/logout.ts
  src/api/member.ts
  src/api/password.ts
  src/api/password/password.ts
  src/api/reissue.ts
  src/api/user.ts
  src/api/user/delete.ts
  src/api/user/profile/get.ts
  src/api/user/profile/put.ts
  src/app/join/email/page.tsx
  src/app/join/summoner/page.tsx
  src/app/login/page.tsx
  src/app/match/profile/page.tsx
  src/app/matching/complete/page.tsx
  src/app/mypage/profile/page.tsx
  src/app/password/auth/page.tsx
  src/app/password/find/page.tsx
  src/app/password/new/page.tsx
  src/app/user/[id]/page.tsx
  src/components/common/Header.tsx
  src/components/crBoard/PositionBox.tsx
  src/components/createBoard/PostBoard.tsx
  src/components/match/GameStyle.tsx
  src/components/match/Profile.tsx
  src/components/mypage/profile/MyPageProfile.tsx
  src/components/mypage/profile/PasswordModal.tsx
  src/hooks/useJwtError.ts
  src/interface/profile.ts
  src/redux/slices/userSlice.ts
  src/redux/thunks/postSignIn.ts
  src/types/api/api.ts
  src/types/api/email/email.d.ts
  src/types/api/join/join.d.ts
  src/types/api/join/riot.d.ts
  src/types/api/login/login.d.ts
  src/types/api/password/password.d.ts
  src/types/api/reissue/reissue.ts
  src/types/api/user/profile/get.d.ts
  src/types/api/user/profile/put.d.ts
  src/utils/storage.ts
Labels: 🛠feat, 🔗api

#169 [Feat] 채팅창 화면 이동 기능 추가
  src/app/board/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/match/game-mode/page.tsx
  src/app/match/page.tsx
  src/app/match/profile/page.tsx
  src/app/matching/complete/page.tsx
  src/app/matching/progress/page.tsx
  src/app/mypage/blocked/page.tsx
  src/app/mypage/help/page.tsx
  src/app/mypage/notification/page.tsx
  src/app/mypage/post/page.tsx
  src/app/mypage/profile/page.tsx
  src/app/mypage/review/page.tsx
  src/app/mypage/service/page.tsx
  src/app/page.tsx
  src/components/chat/Header.tsx
  src/components/chat/Layout.tsx
  src/components/chat/Tabs.tsx
  src/components/common/ChatButton.tsx
  src/components/common/Footer.tsx
  src/components/common/Input.tsx
  src/components/user/BlindProfile.tsx
  src/components/user/UserProfile.tsx
  src/redux/slices/chatPositionSlice.ts
  src/redux/store.ts
  src/utils/storage.ts
Labels: 🛠feat

#172 [Feat] board 타입 적용 및 API 연결
  src/api/board.ts
  src/app/matching/progress/page.tsx
  src/components/board/Table.tsx
  src/components/common/MannerLevelBox.tsx
  src/components/crBoard/User.tsx
  src/components/mypage/post/Post.tsx
  src/components/readBoard/Champion.tsx
  src/components/readBoard/ReadBoard.tsx
  src/components/readBoard/WinningRate.tsx
  src/interface/board.ts
  src/interface/manner.ts
  src/types/api/board/board.d.ts
Labels: 🛠feat, 🔗api

#176 [Feat] 매너 평가 API v2 연결
  src/api/manner.ts
  src/api/user.ts
  src/app/mypage/review/page.tsx
  src/app/user/[id]/page.tsx
  src/components/chat/ChatLayout.tsx
  src/components/chat/Layout.tsx
  src/components/common/ChatButton.tsx
  src/components/common/MannerLevelBox.tsx
  src/components/user/UserProfile.tsx
  src/interface/manner.ts
  src/types/api/manner/manner.d.ts
Labels: 🛠feat, 🔗api
