Repository Gamegoo-repo/Gamegoo-front, pull requests merged in 2025-04, with the labels that each got.

#220 [Test] 라이엇 token 발급 테스트
  src/app/oauth/page.tsx
Labels: 🚧test

#221 [Test] 라이엇 테스트 요청 url 오타 수정
  src/app/oauth/page.tsx
Labels: 🚧test

#215 [Feat] 게시판 메모 기능 추가
  src/app/match/page.tsx
  src/app/page.tsx
  src/components/board/Table.tsx
  src/components/chat/Layout.tsx
  src/components/match/GraphicBox.tsx
  src/constants/board.ts
  src/interface/board.ts
  src/styles/theme.ts
Labels: 🛠feat

#224 [Feat] 챔피언 상세 정보 추가
  src/components/board/Table.tsx
  src/components/match/Profile.tsx
  src/components/readBoard/Champion.tsx
  src/components/readBoard/ReadBoard.tsx
  src/components/user/UserProfile.tsx
  src/interface/board.ts
  src/interface/profile.ts
  src/styles/animation.ts
Labels: 🛠feat

#225 [Feat] Riot 로그인
  package-lock.json
  package.json
  src/api/riot/join.ts
  src/app/board/page.tsx
  src/app/oauth/page.tsx
  src/app/riot/callback/page.tsx
  src/app/riot/page.tsx
  src/components/readBoard/Champion.tsx
  src/data/profile/default.ts
  src/interface/board.ts
  src/interface/profile.ts
  src/redux/slices/userSlice.ts
  src/types/api/board/board.d.ts
  src/types/api/riot/join.d.ts
Labels: 🛠feat

#226 [Feat] 세션을 무시하고 항상 라이엇 로그인창으로 이동
  src/app/riot/page.tsx
Labels: 🛠feat

#227 [Fix] 콜백 중복 요청 제거
  src/app/oauth/page.tsx
Labels: 🔧fix

#233 [Design] 내 프로필 매너레벨 확인 추가
  src/components/common/MannerLevelBox.tsx
  src/components/common/PositionCategory.tsx
  src/components/match/Profile.tsx
  src/components/match/SquareProfile.tsx
  src/components/readBoard/Champion.tsx
Labels: 💄design

#235 [Design] 홈/푸터 반응형 작업
  public/assets/icons/logo_gray.svg
  public/assets/icons/send.svg
  public/assets/images/card/board_mo.png
  public/assets/images/card/matching_mo.png
  src/app/page.tsx
  src/components/common/Banner.tsx
  src/components/common/FeedbackInput.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/HeaderTitle.tsx
  src/components/common/Input.tsx
  src/constants/match.ts
Labels: 💄design

#237 [Fix] Champion 관련 타입 반영 및 게시판 포지션 필터링 오류 수정
  src/app/board/page.tsx
  src/components/board/Table.tsx
  src/components/readBoard/Champion.tsx
  src/components/readBoard/ReadBoard.tsx
  src/components/user/BlindProfile.tsx
  src/components/user/UserProfile.tsx
  src/interface/board.ts
  src/interface/profile.ts
  src/redux/slices/userSlice.ts
  src/types/api/board/board.d.ts
  src/types/api/champion/champion.ts
Labels: 🔧fix
